# Generated by Django 6.0.4 on 2026-05-10 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title_ru', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('start_month', models.IntegerField(blank=True, null=True)),
                ('start_day', models.IntegerField(blank=True, null=True)),
                ('start_easter_offset', models.IntegerField(blank=True, null=True)),
                ('end_month', models.IntegerField(blank=True, null=True)),
                ('end_day', models.IntegerField(blank=True, null=True)),
                ('end_easter_offset', models.IntegerField(blank=True, null=True)),
                ('schedule_json', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='FastType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title_ru', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Feast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feast_type', models.CharField(choices=[('typikon', 'Типикон'), ('lives', 'Жития святых'), ('movable', 'Подвижный')], max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=50)),
                ('title_ru', models.CharField(max_length=500)),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('easter_offset', models.IntegerField(blank=True, null=True)),
                ('troparion_title', models.CharField(blank=True, max_length=500)),
                ('troparion_content', models.TextField(blank=True)),
                ('troparion_echo', models.IntegerField(blank=True, null=True)),
                ('kontakion_title', models.CharField(blank=True, max_length=500)),
                ('kontakion_content', models.TextField(blank=True)),
                ('kontakion_echo', models.IntegerField(blank=True, null=True)),
                ('life_title', models.CharField(blank=True, max_length=500)),
                ('life_content', models.TextField(blank=True)),
                ('refs', models.ManyToManyField(blank=True, to='calendar_app.feast')),
            ],
        ),
        migrations.CreateModel(
            name='DayInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_gregorian', models.DateField(unique=True)),
                ('julian_month', models.IntegerField()),
                ('julian_day', models.IntegerField()),
                ('fast_name', models.CharField(blank=True, max_length=200)),
                ('gospel_reading', models.TextField(blank=True)),
                ('apostolic_reading', models.TextField(blank=True)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('fast_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calendar_app.fasttype')),
                ('feasts', models.ManyToManyField(related_name='days', to='calendar_app.feast')),
            ],
        ),
        migrations.AddIndex(
            model_name='feast',
            index=models.Index(fields=['month', 'day'], name='calendar_ap_month_28a542_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feast',
            unique_together={('month', 'day', 'feast_type')},
        ),
    ]
