# Generated by Django 6.0.4 on 2026-05-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='feast',
            name='calendar_ap_month_28a542_idx',
        ),
        migrations.AlterUniqueTogether(
            name='feast',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='feast',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feast',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='feast',
            index=models.Index(fields=['month', 'day', 'feast_type'], name='calendar_ap_month_c7479e_idx'),
        ),
    ]
