# Generated by Django 6.0.4 on 2026-05-10 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_remove_feast_calendar_ap_month_28a542_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayinfo',
            options={'ordering': ['date_gregorian'], 'verbose_name': 'День', 'verbose_name_plural': 'Дни'},
        ),
        migrations.AlterModelOptions(
            name='fast',
            options={'ordering': ['order', 'title_ru'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterModelOptions(
            name='fasttype',
            options={'verbose_name': 'Тип поста', 'verbose_name_plural': 'Типы постов'},
        ),
        migrations.AlterModelOptions(
            name='feast',
            options={'ordering': ['month', 'day'], 'verbose_name': 'Праздник', 'verbose_name_plural': 'Праздники'},
        ),
        migrations.AddField(
            model_name='feast',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='saints_icons/', verbose_name='Икона (файл)'),
        ),
        migrations.AddField(
            model_name='feast',
            name='icon_url',
            field=models.URLField(blank=True, null=True, verbose_name='Икона (URL)'),
        ),
        migrations.AlterField(
            model_name='dayinfo',
            name='apostolic_reading',
            field=models.TextField(blank=True, verbose_name='Апостольское чтение'),
        ),
        migrations.AlterField(
            model_name='dayinfo',
            name='date_gregorian',
            field=models.DateField(unique=True, verbose_name='Дата (новый стиль)'),
        ),
        migrations.AlterField(
            model_name='dayinfo',
            name='fast_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название поста'),
        ),
        migrations.AlterField(
            model_name='dayinfo',
            name='fast_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calendar_app.fasttype', verbose_name='Тип поста'),
        ),
        migrations.AlterField(
            model_name='dayinfo',
            name='feasts',
            field=models.ManyToManyField(related_name='days', to='calendar_app.feast', verbose_name='Праздники'),
        ),
        migrations.AlterField(
            model_name='dayinfo',
            name='gospel_reading',
            field=models.TextField(blank=True, verbose_name='Евангельское чтение'),
        ),
        migrations.AlterField(
            model_name='dayinfo',
            name='julian_day',
            field=models.IntegerField(verbose_name='День (старый стиль)'),
        ),
        migrations.AlterField(
            model_name='dayinfo',
            name='julian_month',
            field=models.IntegerField(verbose_name='Месяц (старый стиль)'),
        ),
        migrations.AlterField(
            model_name='dayinfo',
            name='summary',
            field=models.CharField(blank=True, max_length=500, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='fast',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='fast',
            name='end_day',
            field=models.IntegerField(blank=True, null=True, verbose_name='Окончание - день'),
        ),
        migrations.AlterField(
            model_name='fast',
            name='end_easter_offset',
            field=models.IntegerField(blank=True, null=True, verbose_name='Окончание - от Пасхи'),
        ),
        migrations.AlterField(
            model_name='fast',
            name='end_month',
            field=models.IntegerField(blank=True, null=True, verbose_name='Окончание - месяц'),
        ),
        migrations.AlterField(
            model_name='fast',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='fast',
            name='schedule_json',
            field=models.JSONField(default=dict, verbose_name='Расписание'),
        ),
        migrations.AlterField(
            model_name='fast',
            name='start_day',
            field=models.IntegerField(blank=True, null=True, verbose_name='Начало - день'),
        ),
        migrations.AlterField(
            model_name='fast',
            name='start_easter_offset',
            field=models.IntegerField(blank=True, null=True, verbose_name='Начало - от Пасхи'),
        ),
        migrations.AlterField(
            model_name='fast',
            name='start_month',
            field=models.IntegerField(blank=True, null=True, verbose_name='Начало - месяц'),
        ),
        migrations.AlterField(
            model_name='fast',
            name='title_ru',
            field=models.CharField(max_length=200, verbose_name='Название (рус.)'),
        ),
        migrations.AlterField(
            model_name='fasttype',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='fasttype',
            name='title_ru',
            field=models.CharField(max_length=200, verbose_name='Название (рус.)'),
        ),
        migrations.AlterField(
            model_name='feast',
            name='day',
            field=models.IntegerField(blank=True, null=True, verbose_name='День (старый стиль)'),
        ),
        migrations.AlterField(
            model_name='feast',
            name='easter_offset',
            field=models.IntegerField(blank=True, null=True, verbose_name='Смещение от Пасхи (дней)'),
        ),
        migrations.AlterField(
            model_name='feast',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Внешний ID'),
        ),
        migrations.AlterField(
            model_name='feast',
            name='feast_type',
            field=models.CharField(choices=[('typikon', 'Типикон'), ('lives', 'Жития святых'), ('movable', 'Подвижный')], max_length=20, verbose_name='Тип праздника'),
        ),
        migrations.AlterField(
            model_name='feast',
            name='kontakion_content',
            field=models.TextField(blank=True, verbose_name='Кондак - текст'),
        ),
        migrations.AlterField(
            model_name='feast',
            name='kontakion_echo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кондак - глас'),
        ),
        migrations.AlterField(
            model_name='feast',
            name='kontakion_title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Кондак - название'),
        ),
        migrations.AlterField(
            model_name='feast',
            name='life_content',
            field=models.TextField(blank=True, verbose_name='Житие - текст'),
        ),
        migrations.AlterField(
            model_name='feast',
            name='life_title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Житие - заголовок'),
        ),
        migrations.AlterField(
            model_name='feast',
            name='month',
            field=models.IntegerField(blank=True, null=True, verbose_name='Месяц (старый стиль)'),
        ),
        migrations.AlterField(
            model_name='feast',
            name='refs',
            field=models.ManyToManyField(blank=True, to='calendar_app.feast', verbose_name='Связанные праздники'),
        ),
        migrations.AlterField(
            model_name='feast',
            name='title_ru',
            field=models.CharField(max_length=500, verbose_name='Название (рус.)'),
        ),
        migrations.AlterField(
            model_name='feast',
            name='troparion_content',
            field=models.TextField(blank=True, verbose_name='Тропарь - текст'),
        ),
        migrations.AlterField(
            model_name='feast',
            name='troparion_echo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Тропарь - глас'),
        ),
        migrations.AlterField(
            model_name='feast',
            name='troparion_title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Тропарь - название'),
        ),
        migrations.AddIndex(
            model_name='dayinfo',
            index=models.Index(fields=['date_gregorian'], name='calendar_ap_date_gr_fb4ae2_idx'),
        ),
    ]
