# Generated by Django 6.0.4 on 2026-05-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_alter_dayinfo_options_alter_fast_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayinfo',
            name='short_summary',
            field=models.CharField(blank=True, max_length=200, verbose_name='Краткое описание (для календаря)'),
        ),
        migrations.AddField(
            model_name='feast',
            name='short_title_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Краткое название (для календаря)'),
        ),
    ]
