# Generated by Django 6.0.4 on 2026-05-15 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0004_dayinfo_short_summary_feast_short_title_ru'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeastDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_type', models.CharField(choices=[('main', 'Основная дата'), ('birth', 'Рождество'), ('death', 'Преставление'), ('relics', 'Обретение мощей'), ('council', 'Собор'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип даты')),
                ('month', models.IntegerField(verbose_name='Месяц (ст.стиль)')),
                ('day', models.IntegerField(verbose_name='День (ст.стиль)')),
                ('easter_offset', models.IntegerField(blank=True, null=True, verbose_name='Смещение от Пасхи')),
                ('title_ru', models.CharField(max_length=500, verbose_name='Название')),
                ('short_title_ru', models.CharField(blank=True, max_length=100, verbose_name='Краткое название')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='saints_icons/', verbose_name='Икона')),
                ('icon_url', models.URLField(blank=True, null=True, verbose_name='URL иконы')),
                ('troparion_title', models.CharField(blank=True, max_length=500, verbose_name='Тропарь - название')),
                ('troparion_content', models.TextField(blank=True, verbose_name='Тропарь - текст')),
                ('troparion_echo', models.IntegerField(blank=True, null=True, verbose_name='Тропарь - глас')),
                ('kontakion_title', models.CharField(blank=True, max_length=500, verbose_name='Кондак - название')),
                ('kontakion_content', models.TextField(blank=True, verbose_name='Кондак - текст')),
                ('kontakion_echo', models.IntegerField(blank=True, null=True, verbose_name='Кондак - глас')),
                ('life_title', models.CharField(blank=True, max_length=500, verbose_name='Житие - заголовок')),
                ('life_content', models.TextField(blank=True, verbose_name='Житие - текст')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Пояснение')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Дата празднования',
                'verbose_name_plural': 'Даты празднования',
                'ordering': ['order', 'month', 'day'],
            },
        ),
        migrations.AlterModelOptions(
            name='feast',
            options={'ordering': ['search_name'], 'verbose_name': 'Святой/праздник', 'verbose_name_plural': 'Святые/праздники'},
        ),
        migrations.RemoveIndex(
            model_name='feast',
            name='calendar_ap_month_c7479e_idx',
        ),
        migrations.AddField(
            model_name='feast',
            name='search_name',
            field=models.CharField(default='temp', max_length=500, verbose_name='Имя для поиска'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dayinfo',
            name='feasts',
            field=models.ManyToManyField(blank=True, related_name='days', to='calendar_app.feast', verbose_name='Праздники (старое)'),
        ),
        migrations.AlterField(
            model_name='dayinfo',
            name='summary',
            field=models.CharField(blank=True, max_length=500, verbose_name='Краткое описание (полное)'),
        ),
        migrations.AlterField(
            model_name='feast',
            name='feast_type',
            field=models.CharField(choices=[('typikon', 'Типикон'), ('lives', 'Жития святых'), ('movable', 'Подвижный')], max_length=20, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='feastdate',
            name='feast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='calendar_app.feast', verbose_name='Святой/праздник'),
        ),
        migrations.AddField(
            model_name='dayinfo',
            name='feast_dates',
            field=models.ManyToManyField(blank=True, related_name='days', to='calendar_app.feastdate', verbose_name='Праздники'),
        ),
        migrations.RemoveField(
            model_name='feast',
            name='day',
        ),
        migrations.RemoveField(
            model_name='feast',
            name='easter_offset',
        ),
        migrations.RemoveField(
            model_name='feast',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='feast',
            name='icon_url',
        ),
        migrations.RemoveField(
            model_name='feast',
            name='kontakion_content',
        ),
        migrations.RemoveField(
            model_name='feast',
            name='kontakion_echo',
        ),
        migrations.RemoveField(
            model_name='feast',
            name='kontakion_title',
        ),
        migrations.RemoveField(
            model_name='feast',
            name='life_content',
        ),
        migrations.RemoveField(
            model_name='feast',
            name='life_title',
        ),
        migrations.RemoveField(
            model_name='feast',
            name='month',
        ),
        migrations.RemoveField(
            model_name='feast',
            name='refs',
        ),
        migrations.RemoveField(
            model_name='feast',
            name='short_title_ru',
        ),
        migrations.RemoveField(
            model_name='feast',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='feast',
            name='troparion_content',
        ),
        migrations.RemoveField(
            model_name='feast',
            name='troparion_echo',
        ),
        migrations.RemoveField(
            model_name='feast',
            name='troparion_title',
        ),
        migrations.AlterUniqueTogether(
            name='feastdate',
            unique_together={('feast', 'month', 'day')},
        ),
    ]
