# Generated by Django 6.0.4 on 2026-05-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0005_feastdate_alter_feast_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feastdate',
            name='celebration_rank',
            field=models.CharField(blank=True, choices=[('vigil', 'Всенощное бдение'), ('polyeleos', 'Полиелей'), ('six_stichera', 'Шестеричный'), ('great_doxology', 'Славословный'), ('ordinary', 'Обычный'), ('', 'Не указан')], default='', max_length=30, verbose_name='Ранг праздника (vigil/polyeleos/etc)'),
        ),
        migrations.AddField(
            model_name='feastdate',
            name='celebration_type',
            field=models.CharField(blank=True, choices=[('great', 'Великий'), ('middle', 'Средний'), ('low', 'Малый'), ('', 'Не указан')], default='', max_length=20, verbose_name='Тип праздника (great/middle/low)'),
        ),
    ]
