# Generated by Django 6.0.4 on 2026-05-15 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0006_feastdate_celebration_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayinfo',
            name='main_feast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_for_days', to='calendar_app.feastdate', verbose_name='Главный святой дня'),
        ),
    ]
