# Generated by Django 6.0.4 on 2026-06-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0007_dayinfo_main_feast'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayinfo',
            name='apostolic_reading_uk',
            field=models.TextField(blank=True, verbose_name='Апостольское чтение (укр.)'),
        ),
        migrations.AddField(
            model_name='dayinfo',
            name='fast_name_uk',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название поста (укр.)'),
        ),
        migrations.AddField(
            model_name='dayinfo',
            name='gospel_reading_uk',
            field=models.TextField(blank=True, verbose_name='Евангельское чтение (укр.)'),
        ),
        migrations.AddField(
            model_name='dayinfo',
            name='short_summary_uk',
            field=models.CharField(blank=True, max_length=200, verbose_name='Краткое описание (для календаря, укр.)'),
        ),
        migrations.AddField(
            model_name='dayinfo',
            name='summary_uk',
            field=models.CharField(blank=True, max_length=500, verbose_name='Краткое описание (полное, укр.)'),
        ),
        migrations.AddField(
            model_name='fast',
            name='title_uk',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название (укр.)'),
        ),
        migrations.AddField(
            model_name='fasttype',
            name='title_uk',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название (укр.)'),
        ),
        migrations.AddField(
            model_name='feastdate',
            name='description_uk',
            field=models.CharField(blank=True, max_length=200, verbose_name='Пояснение (укр.)'),
        ),
        migrations.AddField(
            model_name='feastdate',
            name='kontakion_content_uk',
            field=models.TextField(blank=True, verbose_name='Кондак - текст (укр.)'),
        ),
        migrations.AddField(
            model_name='feastdate',
            name='kontakion_title_uk',
            field=models.CharField(blank=True, max_length=500, verbose_name='Кондак - название (укр.)'),
        ),
        migrations.AddField(
            model_name='feastdate',
            name='life_content_uk',
            field=models.TextField(blank=True, verbose_name='Житие - текст (укр.)'),
        ),
        migrations.AddField(
            model_name='feastdate',
            name='life_title_uk',
            field=models.CharField(blank=True, max_length=500, verbose_name='Житие - заголовок (укр.)'),
        ),
        migrations.AddField(
            model_name='feastdate',
            name='short_title_uk',
            field=models.CharField(blank=True, max_length=100, verbose_name='Краткое название (укр.)'),
        ),
        migrations.AddField(
            model_name='feastdate',
            name='title_uk',
            field=models.CharField(blank=True, max_length=500, verbose_name='Название (укр.)'),
        ),
        migrations.AddField(
            model_name='feastdate',
            name='troparion_content_uk',
            field=models.TextField(blank=True, verbose_name='Тропарь - текст (укр.)'),
        ),
        migrations.AddField(
            model_name='feastdate',
            name='troparion_title_uk',
            field=models.CharField(blank=True, max_length=500, verbose_name='Тропарь - название (укр.)'),
        ),
    ]
