# Generated by Django 6.0.4 on 2026-06-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0008_dayinfo_apostolic_reading_uk_dayinfo_fast_name_uk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feastdate',
            name='day',
            field=models.IntegerField(blank=True, null=True, verbose_name='День (ст.стиль)'),
        ),
        migrations.AlterField(
            model_name='feastdate',
            name='month',
            field=models.IntegerField(blank=True, null=True, verbose_name='Месяц (ст.стиль)'),
        ),
    ]
