# Generated by Django 6.0.4 on 2026-06-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0009_alter_feastdate_day_alter_feastdate_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayinfo',
            name='apostolic_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок Апостола (рус.)'),
        ),
        migrations.AddField(
            model_name='dayinfo',
            name='apostolic_title_uk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок Апостола (укр.)'),
        ),
        migrations.AddField(
            model_name='dayinfo',
            name='gospel_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок Евангелия(рус.)'),
        ),
        migrations.AddField(
            model_name='dayinfo',
            name='gospel_title_uk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок Евангелия (укр.)'),
        ),
    ]
