# Generated by Django 6.0.4 on 2026-06-28 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0010_dayinfo_apostolic_title_dayinfo_apostolic_title_uk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='saints_icons/', verbose_name='Икона')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основная икона')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feast_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='calendar_app.feastdate', verbose_name='Святой/праздник')),
            ],
            options={
                'verbose_name': 'Икона',
                'verbose_name_plural': 'Иконы',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
