# Generated by Django 6.0.4 on 2026-04-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
