# Generated by Django 6.0.4 on 2026-06-01 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_schedule_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Расписания', 'verbose_name_plural': 'Расписания'},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'verbose_name': 'Типы служб', 'verbose_name_plural': 'Типы служб'},
        ),
    ]
