# Generated by Django 6.0.4 on 2026-06-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_schedule_options_alter_servicetype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписания'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Служба', 'verbose_name_plural': 'Службы'},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'verbose_name': 'Тип службы', 'verbose_name_plural': 'Типы служб'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='custom_title',
        ),
        migrations.AddField(
            model_name='service',
            name='custom_title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название (рус.)'),
        ),
        migrations.AddField(
            model_name='service',
            name='custom_title_uk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название (укр.)'),
        ),
    ]
