# Generated by Django 6.0.4 on 2026-06-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Название (ru)')),
                ('title_uk', models.CharField(blank=True, max_length=200, verbose_name='Название (uk)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (ru)')),
                ('description_uk', models.TextField(blank=True, verbose_name='Описание (uk)')),
                ('media_type', models.CharField(choices=[('photo', 'Фото'), ('video', 'Видео')], db_index=True, max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/photos/', verbose_name='Фото')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='gallery/videos/', verbose_name='Видео файл')),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='gallery/thumbnails/', verbose_name='Превью видео')),
                ('order', models.IntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Медиа галерея',
                'verbose_name_plural': 'Медиа галерея',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
