# Generated by Django 6.0.4 on 2026-06-09 06:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediagallery',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='mediagallery',
            name='video_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='mediagallery',
            name='video_thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Превью видео'),
        ),
    ]
