# Generated by Django 6.0.4 on 2026-06-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_mediagallery_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediagallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='mediagallery',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='gallery/videos/', verbose_name='Видео файл'),
        ),
        migrations.AlterField(
            model_name='mediagallery',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/thumbnails/', verbose_name='Превью видео'),
        ),
    ]
