# Generated by Django 6.0.4 on 2026-06-09 07:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_mediagallery_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediagallery',
            name='video_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Видео'),
        ),
    ]
