# Generated by Django 6.0.4 on 2026-05-26 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0002_schedule_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrebaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('price_type', models.CharField(choices=[('fixed', 'фиксированная'), ('per_name', 'за имя')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('service_types', models.ManyToManyField(related_name='treba_types', to='schedule.servicetype')),
            ],
        ),
        migrations.CreateModel(
            name='TrebaOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.JSONField(default=list)),
                ('customers_name', models.CharField(blank=True, max_length=255)),
                ('customers_phone', models.CharField(blank=True, max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплату'), ('paid', 'Оплачено'), ('canceled', 'отмененно')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treba_orders', to='schedule.schedule')),
                ('treba_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='treby.trebatype')),
            ],
        ),
    ]
