# Generated by Django 6.0.4 on 2026-05-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treby', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trebaorder',
            old_name='customers_name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='trebaorder',
            old_name='customers_phone',
            new_name='customer_phone',
        ),
        migrations.AlterField(
            model_name='trebaorder',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trebaorder',
            name='names',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
