# Generated by Django 6.0.4 on 2026-05-26 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treby', '0002_rename_customers_name_trebaorder_customer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrebaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrebaVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='trebatype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='trebatype',
            name='slug',
        ),
        migrations.AlterField(
            model_name='trebaorder',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trebaorder',
            name='names',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='trebaorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплату'), ('paid', 'Оплачено'), ('canceled', 'Отменено')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='trebatype',
            name='price_type',
            field=models.CharField(choices=[('fixed', 'Фиксированная'), ('per_name', 'За имя')], max_length=20),
        ),
        migrations.AddField(
            model_name='trebatype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='treby.trebacategory'),
        ),
        migrations.AddField(
            model_name='trebatype',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types', to='treby.trebavariant'),
        ),
    ]
