# Generated by Django 6.0.4 on 2026-05-26 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_schedule_is_active'),
        ('treby', '0003_trebacategory_trebavariant_remove_trebatype_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trebaorder',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя подателя'),
        ),
        migrations.AlterField(
            model_name='trebaorder',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='trebatype',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='treby.trebacategory'),
        ),
        migrations.AlterField(
            model_name='trebatype',
            name='service_types',
            field=models.ManyToManyField(blank=True, related_name='treba_types', to='schedule.servicetype'),
        ),
    ]
