# Generated by Django 6.0.4 on 2026-05-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treby', '0004_alter_trebaorder_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trebaorder',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
        migrations.AddField(
            model_name='trebaorder',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID платежа LiqPay'),
        ),
    ]
