# Generated by Django 6.0.4 on 2026-05-26 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treby', '0005_trebaorder_is_paid_trebaorder_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trebaorder',
            name='is_paid',
        ),
    ]
