# Generated by Django 6.0.4 on 2026-05-27 03:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treby', '0006_remove_trebaorder_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='trebaorder',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trebaorder',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='trebaorder',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='trebaorder',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='trebaorder',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
