# Generated by Django 6.0.4 on 2026-05-27 03:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treby', '0007_trebaorder_paid_at_trebaorder_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trebaorder',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
