# Generated by Django 6.0.4 on 2026-05-27 03:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treby', '0008_alter_trebaorder_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trebaorder',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
