# Generated by Django 6.0.4 on 2026-05-27 03:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treby', '0009_alter_trebaorder_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trebacategory',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='trebaorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='trebatype',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='trebavariant',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='trebaorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='trebaorder',
            name='payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trebaorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплату'), ('paid', 'Оплачено'), ('canceled', 'Отменено')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='trebaorder',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='trebatype',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
