# Generated by Django 6.0.4 on 2026-05-27 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_schedule_is_active'),
        ('treby', '0010_alter_trebacategory_options_alter_trebaorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trebatype',
            name='requires_schedule',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='trebaorder',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treba_orders', to='schedule.schedule'),
        ),
    ]
