# Generated by Django 6.0.4 on 2026-05-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treby', '0011_trebatype_requires_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trebaorder',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
