# Generated by Django 6.0.4 on 2026-06-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treby', '0012_trebaorder_customer_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trebacategory',
            options={'ordering': ['name'], 'verbose_name': 'Категория требы', 'verbose_name_plural': 'Категории треб'},
        ),
        migrations.AlterModelOptions(
            name='trebaorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ (записка)', 'verbose_name_plural': 'Заказы (записки)'},
        ),
        migrations.AlterModelOptions(
            name='trebatype',
            options={'ordering': ['id'], 'verbose_name': 'Тип требы', 'verbose_name_plural': 'Типы треб'},
        ),
        migrations.AlterModelOptions(
            name='trebavariant',
            options={'ordering': ['name'], 'verbose_name': 'Вариант требы', 'verbose_name_plural': 'Варианты треб'},
        ),
        migrations.AddField(
            model_name='trebaorder',
            name='additional_info',
            field=models.TextField(blank=True, verbose_name='Дополнительная информация'),
        ),
    ]
