# Generated by Django 6.0.4 on 2026-04-14 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_text_news_content_news_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='created',
            new_name='created_at',
        ),
    ]
